[2025-02-18T14:21:33.107+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T14:21:33.122+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_streaming_process_pipeline.stream_processor manual__2025-02-18T14:21:32.294696+00:00 [queued]>
[2025-02-18T14:21:33.129+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_streaming_process_pipeline.stream_processor manual__2025-02-18T14:21:32.294696+00:00 [queued]>
[2025-02-18T14:21:33.129+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T14:21:33.140+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): stream_processor> on 2025-02-18 14:21:32.294696+00:00
[2025-02-18T14:21:33.146+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_streaming_process_pipeline', 'stream_processor', 'manual__2025-02-18T14:21:32.294696+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/kafka_streaming_process.py', '--cfg-path', '/tmp/tmpur3q1ifh']
[2025-02-18T14:21:33.149+0000] {standard_task_runner.py:105} INFO - Job 105: Subtask stream_processor
[2025-02-18T14:21:33.150+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=198) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-18T14:21:33.150+0000] {standard_task_runner.py:72} INFO - Started process 200 to run task
[2025-02-18T14:21:33.185+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_streaming_process_pipeline.stream_processor manual__2025-02-18T14:21:32.294696+00:00 [running]> on host 944871224fc0
[2025-02-18T14:21:33.262+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_streaming_process_pipeline' AIRFLOW_CTX_TASK_ID='stream_processor' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T14:21:32.294696+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T14:21:32.294696+00:00'
[2025-02-18T14:21:33.263+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T14:21:33.281+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-18T14:21:33.282+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /usr/local/app/services/spark_streaming_processor.py']
[2025-02-18T14:21:33.290+0000] {subprocess.py:99} INFO - Output:
[2025-02-18T14:21:35.186+0000] {subprocess.py:106} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-02-18T14:21:35.912+0000] {subprocess.py:106} INFO - %6|1739888495.912|GETSUBSCRIPTIONS|ccloud-python-client-00816959-7fc0-4d75-98d8-88c7998cc97d#producer-1| [thrd:main]: Telemetry client instance id changed from AAAAAAAAAAAAAAAAAAAAAA to DdXWO4JoQ1egX4ZvqcUchg
[2025-02-18T14:21:36.715+0000] {subprocess.py:106} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.12/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-18T14:21:36.785+0000] {subprocess.py:106} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-02-18T14:21:36.786+0000] {subprocess.py:106} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-02-18T14:21:36.789+0000] {subprocess.py:106} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-02-18T14:21:36.790+0000] {subprocess.py:106} INFO - net.snowflake#spark-snowflake_2.12 added as a dependency
[2025-02-18T14:21:36.791+0000] {subprocess.py:106} INFO - net.snowflake#snowflake-jdbc added as a dependency
[2025-02-18T14:21:36.791+0000] {subprocess.py:106} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-6c47b84d-ceb5-46ce-b5ee-a59e6c9fe9f0;1.0
[2025-02-18T14:21:36.791+0000] {subprocess.py:106} INFO - 	confs: [default]
[2025-02-18T14:21:39.613+0000] {subprocess.py:106} INFO - 	found org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.0 in central
[2025-02-18T14:21:39.863+0000] {subprocess.py:106} INFO - 	found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.0 in central
[2025-02-18T14:21:39.969+0000] {subprocess.py:106} INFO - 	found org.apache.kafka#kafka-clients;3.3.2 in central
[2025-02-18T14:21:40.074+0000] {subprocess.py:106} INFO - 	found org.lz4#lz4-java;1.8.0 in central
[2025-02-18T14:21:40.191+0000] {subprocess.py:106} INFO - 	found org.xerial.snappy#snappy-java;1.1.9.1 in central
[2025-02-18T14:21:40.785+0000] {subprocess.py:106} INFO - 	found org.slf4j#slf4j-api;2.0.6 in central
[2025-02-18T14:21:42.532+0000] {subprocess.py:106} INFO - 	found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-02-18T14:21:42.658+0000] {subprocess.py:106} INFO - 	found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-02-18T14:21:43.625+0000] {subprocess.py:106} INFO - 	found commons-logging#commons-logging;1.1.3 in central
[2025-02-18T14:21:43.726+0000] {subprocess.py:106} INFO - 	found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-02-18T14:21:45.389+0000] {subprocess.py:106} INFO - 	found org.apache.commons#commons-pool2;2.11.1 in central
[2025-02-18T14:21:46.939+0000] {subprocess.py:106} INFO - 	found net.snowflake#snowflake-jdbc;3.13.14 in central
[2025-02-18T14:21:46.990+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.4.0/spark-sql-kafka-0-10_2.12-3.4.0.jar ...
[2025-02-18T14:21:47.100+0000] {subprocess.py:106} INFO - 	[SUCCESSFUL ] org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.0!spark-sql-kafka-0-10_2.12.jar (155ms)
[2025-02-18T14:21:47.146+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.13.14/snowflake-jdbc-3.13.14.jar ...
[2025-02-18T14:21:53.780+0000] {subprocess.py:106} INFO - 	[SUCCESSFUL ] net.snowflake#snowflake-jdbc;3.13.14!snowflake-jdbc.jar (6680ms)
[2025-02-18T14:21:53.825+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.4.0/spark-token-provider-kafka-0-10_2.12-3.4.0.jar ...
[2025-02-18T14:21:53.879+0000] {subprocess.py:106} INFO - 	[SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.0!spark-token-provider-kafka-0-10_2.12.jar (98ms)
[2025-02-18T14:21:53.925+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.3.2/kafka-clients-3.3.2.jar ...
[2025-02-18T14:21:55.034+0000] {subprocess.py:106} INFO - 	[SUCCESSFUL ] org.apache.kafka#kafka-clients;3.3.2!kafka-clients.jar (1154ms)
[2025-02-18T14:21:55.078+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
[2025-02-18T14:21:55.127+0000] {subprocess.py:106} INFO - 	[SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (92ms)
[2025-02-18T14:21:55.171+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar ...
[2025-02-18T14:21:55.239+0000] {subprocess.py:106} INFO - 	[SUCCESSFUL ] org.apache.commons#commons-pool2;2.11.1!commons-pool2.jar (112ms)
[2025-02-18T14:21:55.285+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.4/hadoop-client-runtime-3.3.4.jar ...
[2025-02-18T14:22:01.692+0000] {subprocess.py:106} INFO - 	[SUCCESSFUL ] org.apache.hadoop#hadoop-client-runtime;3.3.4!hadoop-client-runtime.jar (6452ms)
[2025-02-18T14:22:01.737+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar ...
[2025-02-18T14:22:01.887+0000] {subprocess.py:106} INFO - 	[SUCCESSFUL ] org.lz4#lz4-java;1.8.0!lz4-java.jar (195ms)
[2025-02-18T14:22:01.932+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.9.1/snappy-java-1.1.9.1.jar ...
[2025-02-18T14:22:02.248+0000] {subprocess.py:106} INFO - 	[SUCCESSFUL ] org.xerial.snappy#snappy-java;1.1.9.1!snappy-java.jar(bundle) (360ms)
[2025-02-18T14:22:02.292+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.6/slf4j-api-2.0.6.jar ...
[2025-02-18T14:22:02.344+0000] {subprocess.py:106} INFO - 	[SUCCESSFUL ] org.slf4j#slf4j-api;2.0.6!slf4j-api.jar (95ms)
[2025-02-18T14:22:02.389+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.4/hadoop-client-api-3.3.4.jar ...
[2025-02-18T14:22:05.820+0000] {subprocess.py:106} INFO - 	[SUCCESSFUL ] org.apache.hadoop#hadoop-client-api;3.3.4!hadoop-client-api.jar (3474ms)
[2025-02-18T14:22:05.864+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
[2025-02-18T14:22:05.919+0000] {subprocess.py:106} INFO - 	[SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (99ms)
[2025-02-18T14:22:05.919+0000] {subprocess.py:106} INFO - :: resolution report :: resolve 10155ms :: artifacts dl 18974ms
[2025-02-18T14:22:05.920+0000] {subprocess.py:106} INFO - 	:: modules in use:
[2025-02-18T14:22:05.920+0000] {subprocess.py:106} INFO - 	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-02-18T14:22:05.920+0000] {subprocess.py:106} INFO - 	commons-logging#commons-logging;1.1.3 from central in [default]
[2025-02-18T14:22:05.920+0000] {subprocess.py:106} INFO - 	net.snowflake#snowflake-jdbc;3.13.14 from central in [default]
[2025-02-18T14:22:05.921+0000] {subprocess.py:106} INFO - 	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-02-18T14:22:05.921+0000] {subprocess.py:106} INFO - 	org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
[2025-02-18T14:22:05.921+0000] {subprocess.py:106} INFO - 	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
[2025-02-18T14:22:05.922+0000] {subprocess.py:106} INFO - 	org.apache.kafka#kafka-clients;3.3.2 from central in [default]
[2025-02-18T14:22:05.922+0000] {subprocess.py:106} INFO - 	org.apache.spark#spark-sql-kafka-0-10_2.12;3.4.0 from central in [default]
[2025-02-18T14:22:05.922+0000] {subprocess.py:106} INFO - 	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.4.0 from central in [default]
[2025-02-18T14:22:05.923+0000] {subprocess.py:106} INFO - 	org.lz4#lz4-java;1.8.0 from central in [default]
[2025-02-18T14:22:05.923+0000] {subprocess.py:106} INFO - 	org.slf4j#slf4j-api;2.0.6 from central in [default]
[2025-02-18T14:22:05.923+0000] {subprocess.py:106} INFO - 	org.xerial.snappy#snappy-java;1.1.9.1 from central in [default]
[2025-02-18T14:22:05.924+0000] {subprocess.py:106} INFO - 	---------------------------------------------------------------------
[2025-02-18T14:22:05.924+0000] {subprocess.py:106} INFO - 	|                  |            modules            ||   artifacts   |
[2025-02-18T14:22:05.924+0000] {subprocess.py:106} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-02-18T14:22:05.924+0000] {subprocess.py:106} INFO - 	---------------------------------------------------------------------
[2025-02-18T14:22:05.925+0000] {subprocess.py:106} INFO - 	|      default     |   13  |   12  |   12  |   0   ||   12  |   12  |
[2025-02-18T14:22:05.925+0000] {subprocess.py:106} INFO - 	---------------------------------------------------------------------
[2025-02-18T14:22:05.925+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.925+0000] {subprocess.py:106} INFO - :: problems summary ::
[2025-02-18T14:22:05.926+0000] {subprocess.py:106} INFO - :::: WARNINGS
[2025-02-18T14:22:05.926+0000] {subprocess.py:106} INFO - 		module not found: net.snowflake#spark-snowflake_2.12;2.9.1
[2025-02-18T14:22:05.926+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.926+0000] {subprocess.py:106} INFO - 	==== local-m2-cache: tried
[2025-02-18T14:22:05.926+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.926+0000] {subprocess.py:106} INFO - 	  file:/home/***/.m2/repository/net/snowflake/spark-snowflake_2.12/2.9.1/spark-snowflake_2.12-2.9.1.pom
[2025-02-18T14:22:05.927+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.927+0000] {subprocess.py:106} INFO - 	  -- artifact net.snowflake#spark-snowflake_2.12;2.9.1!spark-snowflake_2.12.jar:
[2025-02-18T14:22:05.927+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.927+0000] {subprocess.py:106} INFO - 	  file:/home/***/.m2/repository/net/snowflake/spark-snowflake_2.12/2.9.1/spark-snowflake_2.12-2.9.1.jar
[2025-02-18T14:22:05.928+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.928+0000] {subprocess.py:106} INFO - 	==== local-ivy-cache: tried
[2025-02-18T14:22:05.929+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.929+0000] {subprocess.py:106} INFO - 	  /home/***/.ivy2/local/net.snowflake/spark-snowflake_2.12/2.9.1/ivys/ivy.xml
[2025-02-18T14:22:05.930+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.930+0000] {subprocess.py:106} INFO - 	  -- artifact net.snowflake#spark-snowflake_2.12;2.9.1!spark-snowflake_2.12.jar:
[2025-02-18T14:22:05.930+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.931+0000] {subprocess.py:106} INFO - 	  /home/***/.ivy2/local/net.snowflake/spark-snowflake_2.12/2.9.1/jars/spark-snowflake_2.12.jar
[2025-02-18T14:22:05.931+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.931+0000] {subprocess.py:106} INFO - 	==== central: tried
[2025-02-18T14:22:05.932+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.932+0000] {subprocess.py:106} INFO - 	  https://repo1.maven.org/maven2/net/snowflake/spark-snowflake_2.12/2.9.1/spark-snowflake_2.12-2.9.1.pom
[2025-02-18T14:22:05.932+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.932+0000] {subprocess.py:106} INFO - 	  -- artifact net.snowflake#spark-snowflake_2.12;2.9.1!spark-snowflake_2.12.jar:
[2025-02-18T14:22:05.933+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.933+0000] {subprocess.py:106} INFO - 	  https://repo1.maven.org/maven2/net/snowflake/spark-snowflake_2.12/2.9.1/spark-snowflake_2.12-2.9.1.jar
[2025-02-18T14:22:05.933+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.933+0000] {subprocess.py:106} INFO - 	==== spark-packages: tried
[2025-02-18T14:22:05.933+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.934+0000] {subprocess.py:106} INFO - 	  https://repos.spark-packages.org/net/snowflake/spark-snowflake_2.12/2.9.1/spark-snowflake_2.12-2.9.1.pom
[2025-02-18T14:22:05.934+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.935+0000] {subprocess.py:106} INFO - 	  -- artifact net.snowflake#spark-snowflake_2.12;2.9.1!spark-snowflake_2.12.jar:
[2025-02-18T14:22:05.935+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.935+0000] {subprocess.py:106} INFO - 	  https://repos.spark-packages.org/net/snowflake/spark-snowflake_2.12/2.9.1/spark-snowflake_2.12-2.9.1.jar
[2025-02-18T14:22:05.935+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.942+0000] {subprocess.py:106} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-02-18T14:22:05.942+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.943+0000] {subprocess.py:106} INFO - 		::          UNRESOLVED DEPENDENCIES         ::
[2025-02-18T14:22:05.943+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.943+0000] {subprocess.py:106} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-02-18T14:22:05.943+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.944+0000] {subprocess.py:106} INFO - 		:: net.snowflake#spark-snowflake_2.12;2.9.1: not found
[2025-02-18T14:22:05.944+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.945+0000] {subprocess.py:106} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-02-18T14:22:05.945+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.945+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.946+0000] {subprocess.py:106} INFO - 
[2025-02-18T14:22:05.946+0000] {subprocess.py:106} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-02-18T14:22:05.946+0000] {subprocess.py:106} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: net.snowflake#spark-snowflake_2.12;2.9.1: not found]
[2025-02-18T14:22:05.946+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1613)
[2025-02-18T14:22:05.947+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-02-18T14:22:05.947+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:339)
[2025-02-18T14:22:05.947+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:969)
[2025-02-18T14:22:05.948+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:199)
[2025-02-18T14:22:05.948+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:222)
[2025-02-18T14:22:05.948+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2025-02-18T14:22:05.948+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-02-18T14:22:05.949+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-02-18T14:22:05.949+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-02-18T14:22:06.021+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-18T14:22:06.022+0000] {subprocess.py:106} INFO -   File "/usr/local/app/services/spark_streaming_processor.py", line 68, in <module>
[2025-02-18T14:22:06.025+0000] {subprocess.py:106} INFO -     spark_processor = SparkStreamingProcessor(kafka_publisher)
[2025-02-18T14:22:06.025+0000] {subprocess.py:106} INFO -                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-18T14:22:06.026+0000] {subprocess.py:106} INFO -   File "/usr/local/app/services/spark_streaming_processor.py", line 25, in __init__
[2025-02-18T14:22:06.027+0000] {subprocess.py:106} INFO -     .getOrCreate()
[2025-02-18T14:22:06.028+0000] {subprocess.py:106} INFO -      ^^^^^^^^^^^^^
[2025-02-18T14:22:06.028+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
[2025-02-18T14:22:06.028+0000] {subprocess.py:106} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-02-18T14:22:06.028+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-18T14:22:06.029+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
[2025-02-18T14:22:06.029+0000] {subprocess.py:106} INFO -     SparkContext(conf=conf or SparkConf())
[2025-02-18T14:22:06.029+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
[2025-02-18T14:22:06.029+0000] {subprocess.py:106} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-02-18T14:22:06.030+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
[2025-02-18T14:22:06.030+0000] {subprocess.py:106} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-02-18T14:22:06.031+0000] {subprocess.py:106} INFO -                                        ^^^^^^^^^^^^^^^^^^^^
[2025-02-18T14:22:06.031+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
[2025-02-18T14:22:06.031+0000] {subprocess.py:106} INFO -     raise PySparkRuntimeError(
[2025-02-18T14:22:06.032+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-02-18T14:22:06.209+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-18T14:22:06.218+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-18T14:22:06.222+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=kafka_streaming_process_pipeline, task_id=stream_processor, run_id=manual__2025-02-18T14:21:32.294696+00:00, execution_date=20250218T142132, start_date=20250218T142133, end_date=20250218T142206
[2025-02-18T14:22:06.232+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T14:22:06.233+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 105 for task stream_processor (Bash command failed. The command returned a non-zero exit code 1.; 200)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-18T14:22:06.268+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-18T14:22:06.279+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T14:22:06.281+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
