[2025-02-18T14:30:16.422+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T14:30:16.437+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_streaming_process_pipeline.stream_processor manual__2025-02-18T14:30:15.918920+00:00 [queued]>
[2025-02-18T14:30:16.445+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_streaming_process_pipeline.stream_processor manual__2025-02-18T14:30:15.918920+00:00 [queued]>
[2025-02-18T14:30:16.445+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T14:30:16.468+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): stream_processor> on 2025-02-18 14:30:15.918920+00:00
[2025-02-18T14:30:16.475+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_streaming_process_pipeline', 'stream_processor', 'manual__2025-02-18T14:30:15.918920+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/kafka_streaming_process.py', '--cfg-path', '/tmp/tmpt8p6qhv1']
[2025-02-18T14:30:16.477+0000] {standard_task_runner.py:105} INFO - Job 111: Subtask stream_processor
[2025-02-18T14:30:16.478+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1884) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-18T14:30:16.478+0000] {standard_task_runner.py:72} INFO - Started process 1886 to run task
[2025-02-18T14:30:16.512+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_streaming_process_pipeline.stream_processor manual__2025-02-18T14:30:15.918920+00:00 [running]> on host 944871224fc0
[2025-02-18T14:30:16.582+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_streaming_process_pipeline' AIRFLOW_CTX_TASK_ID='stream_processor' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T14:30:15.918920+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T14:30:15.918920+00:00'
[2025-02-18T14:30:16.583+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T14:30:16.597+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-18T14:30:16.598+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /usr/local/app/services/spark_streaming_processor.py']
[2025-02-18T14:30:16.605+0000] {subprocess.py:99} INFO - Output:
[2025-02-18T14:30:18.230+0000] {subprocess.py:106} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-02-18T14:30:18.829+0000] {subprocess.py:106} INFO - %6|1739889018.828|GETSUBSCRIPTIONS|ccloud-python-client-00816959-7fc0-4d75-98d8-88c7998cc97d#producer-1| [thrd:main]: Telemetry client instance id changed from AAAAAAAAAAAAAAAAAAAAAA to ln31OXMMTtq/wkytHKaOMQ
[2025-02-18T14:30:19.955+0000] {subprocess.py:106} INFO - 25/02/18 14:30:19 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-18T14:30:20.115+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-02-18T14:30:20.116+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-02-18T14:30:20.881+0000] {subprocess.py:106} INFO - 25/02/18 14:30:20 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-02-18T14:30:21.966+0000] {subprocess.py:106} INFO - 2025-02-18 14:30:21,966 - INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-02-18T14:30:21.967+0000] {subprocess.py:106} INFO - 2025-02-18 14:30:21,966 - INFO - Connecting to GLOBAL Snowflake domain
[2025-02-18T14:30:21.967+0000] {subprocess.py:106} INFO - 2025-02-18 14:30:21,967 - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-02-18T14:30:21.968+0000] {subprocess.py:106} INFO - 2025-02-18 14:30:21,967 - INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2025-02-18T14:30:22.253+0000] {subprocess.py:106} INFO - 2025-02-18 14:30:22,253 - INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2025-02-18T14:30:22.622+0000] {subprocess.py:106} INFO - 2025-02-18 14:30:22,622 - INFO - ✅ Connected to Snowflake
[2025-02-18T14:30:22.623+0000] {subprocess.py:106} INFO - 2025-02-18 14:30:22,623 - INFO - Starting Spark Streaming Processor...
[2025-02-18T14:30:24.134+0000] {subprocess.py:106} INFO - 2025-02-18 14:30:24,134 - INFO - ✅ Listening for new events...
[2025-02-18T14:32:57.819+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-02-18T14:32:57.820+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-18T14:32:57.822+0000] {process_utils.py:132} INFO - Sending 15 to group 1886. PIDs of all processes in the group: [1889, 1931, 1886]
[2025-02-18T14:32:57.823+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1886
[2025-02-18T14:32:57.825+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-18T14:32:57.825+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2025-02-18T14:32:57.844+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T14:32:57.851+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1886, status='terminated', exitcode=0, started='14:30:15') (1886) terminated with exit code 0
[2025-02-18T14:32:58.225+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1889, status='terminated', started='14:30:15') (1889) terminated with exit code None
[2025-02-18T14:32:58.240+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1931, status='terminated', started='14:30:17') (1931) terminated with exit code None
