[2025-02-17T19:31:20.556+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-17T19:31:20.568+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_streaming_process_pipeline.example_consumer manual__2025-02-17T19:31:08.526389+00:00 [queued]>
[2025-02-17T19:31:20.575+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_streaming_process_pipeline.example_consumer manual__2025-02-17T19:31:08.526389+00:00 [queued]>
[2025-02-17T19:31:20.576+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-17T19:31:20.588+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): example_consumer> on 2025-02-17 19:31:08.526389+00:00
[2025-02-17T19:31:20.593+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_streaming_process_pipeline', 'example_consumer', 'manual__2025-02-17T19:31:08.526389+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/kafka_streaming_process.py', '--cfg-path', '/tmp/tmpqewsg680']
[2025-02-17T19:31:20.595+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask example_consumer
[2025-02-17T19:31:20.595+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1036) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-17T19:31:20.596+0000] {standard_task_runner.py:72} INFO - Started process 1037 to run task
[2025-02-17T19:31:20.625+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_streaming_process_pipeline.example_consumer manual__2025-02-17T19:31:08.526389+00:00 [running]> on host b6abba1bc830
[2025-02-17T19:31:20.685+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_streaming_process_pipeline' AIRFLOW_CTX_TASK_ID='example_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T19:31:08.526389+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-17T19:31:08.526389+00:00'
[2025-02-17T19:31:20.686+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-17T19:31:20.703+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-02-17T19:31:20.704+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077:7077 --conf spark.executor.memory=2g --executor-cores 1 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /usr/local/app/spark_applications/user_activity_consuming.py
[2025-02-17T19:31:20.740+0000] {spark_submit.py:641} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-02-17T19:31:22.896+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-02-17T19:31:22.897+0000] {spark_submit.py:641} INFO - File "/usr/local/app/spark_applications/user_activity_consuming.py", line 3, in <module>
[2025-02-17T19:31:22.899+0000] {spark_submit.py:641} INFO - from ..kafka.Config import producer_conf
[2025-02-17T19:31:22.900+0000] {spark_submit.py:641} INFO - ImportError: attempted relative import with no known parent package
[2025-02-17T19:31:22.941+0000] {spark_submit.py:641} INFO - 25/02/17 19:31:22 INFO ShutdownHookManager: Shutdown hook called
[2025-02-17T19:31:22.945+0000] {spark_submit.py:641} INFO - 25/02/17 19:31:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-cfb4f680-6e2f-4b8d-94dc-6a97f1da92a8
[2025-02-17T19:31:22.974+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077:7077 --conf spark.executor.memory=2g --executor-cores 1 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /usr/local/app/spark_applications/user_activity_consuming.py. Error code is: 1.
[2025-02-17T19:31:22.979+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=kafka_streaming_process_pipeline, task_id=example_consumer, run_id=manual__2025-02-17T19:31:08.526389+00:00, execution_date=20250217T193108, start_date=20250217T193120, end_date=20250217T193122
[2025-02-17T19:31:22.989+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-17T19:31:22.989+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 65 for task example_consumer (Cannot execute: spark-submit --master spark://spark:7077:7077 --conf spark.executor.memory=2g --executor-cores 1 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /usr/local/app/spark_applications/user_activity_consuming.py. Error code is: 1.; 1037)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077:7077 --conf spark.executor.memory=2g --executor-cores 1 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /usr/local/app/spark_applications/user_activity_consuming.py. Error code is: 1.
[2025-02-17T19:31:23.017+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-17T19:31:23.027+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-17T19:31:23.029+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
